# -*- coding: utf-8 -*-
"""OSS_Task_5_26040022.ipnyb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hL59CverczRznmDuI2tODnkD9tDBn2fm

# Contributor Management and Issue Tracking System
"""

"""
Name: Marie Criz Zaragoza
Student ID: 26040022
Course Name: Introduction to Open Source Software
Description: This is a project program is a Contributor Management and Issue
Tracking System in Python.

""";

"""### Shared Helpers"""

# Reusable separators
line = 70 * "="
dash = 70 * "-"


def get_validated_input(prompt, valid_options):
    """
    Helper to repeat input requests until valid data is provided.
    Used across both contributor and issue input collection.
    """
    while True:
        try:

            # Remove trailing whitespaces
            raw = input(prompt).strip()

            # Normalize casing for comparison
            formatted = raw.title()

            if formatted not in valid_options:
                raise ValueError(f"Invalid input. Please choose from: {valid_options}")

            return formatted
        except ValueError as e:
            print(f"Error: {e}")

def get_validated_alpha(prompt, field_name):
    """
    Repeats input until a non-empty, alphabetic-only string is provided.
    Allows spaces (e.g., 'New Zealand', 'Team Lead').
    """
    while True:
        value = input(prompt).strip()
        if value and value.replace(' ', '').isalpha():
            return value.title()
        print(f'  [!] {field_name} cannot be empty or contain numbers/special characters. Try again.')

def get_validated_int(prompt):
    """
    Repeats input until a valid non-negative integer is provided.
    """
    while True:
        raw = input(prompt).strip()
        if raw.isdigit():          # isdigit() naturally rejects negatives and decimals
            return int(raw)
        print('  [!] Commits must be a non-negative integer. Try again.')

"""## Section 1 — Launch Your Project

### 1.1. Getting User Inputs
"""

3# Official project info stored as a Tuple
# Fields: name, version, year started, main language, lead name
project = ("CMITS", 1, 2026, "Python", "Marie Criz Zaragoza")

contributors = []  # Should be four contributors

def get_contributor():
    print("\n--- New Contributor Entry ---")
    name     = get_validated_alpha("Enter contributor name: ", "Name")
    role     = get_validated_alpha("Enter your role: ", "Role")
    language = get_validated_alpha("Enter primary language: ", "Language")
    commits  = get_validated_int("Enter number of commits: ")
    country  = get_validated_alpha("Enter country: ", "Country")

    return {
        "name": name,
        "role": role,
        "language": language,
        "commits": commits,
        "country": country
    }

# Main execution — register exactly 4 contributors
while len(contributors) < 4:
    try:
        contributor = get_contributor()
        contributors.append(contributor)
        print(f"Contributor {len(contributors)}/4 added successfully.")
    except KeyboardInterrupt:
        print("\nProcess interrupted by user.")
        break

print("\nFinal Contributor List:")
for c in contributors:
    print(c)

"""### 1.2. Printing Banner and outputs"""

# Print welcome banner using string repetition
print(line)
print(f" {project[0]} — Contributor Management and Issue Tracking System")
print(f" Project Lead : {project[-1]}")
print(line)

# Print each field using its index
print(f"Name : {project[0]} | Version : {project[1]} | Started : {project[2]}")

# Use slicing to print the first three fields at once
print(f"First 3 fields : {project[:3]}")

# Use count() and index() on the tuple
print(f"Language count : {project.count('Python')} Language index : {project.index('Python')}")

# Tuples are immutable — they suit this data because official project
# info (name, version, year, language, lead) should not be modified
# once set.
print("# project[0] = 'test' --> TypeError: tuple does not support item assignment")

print(dash)

# Extract names into a names list → sort → print → negative index → slice first two
names = []
for c in contributors:
    names.append(c["name"])

names.sort()
print(f"Sorted names : {names}")
print(f"Last name : {names[-1]} First two : {names[:2]}")

print(dash)

# Loop through contributors and use update() to add 'status': 'Active' to each
for c in contributors:
    c.update({"status": "Active"})

# Use get() to print the first contributor's status
print(f"Contributor 1 status : {contributors[0].get('status')}")

# Use copy() to back up the first contributor's dict and print it
backup = contributors[0].copy()
print(f"Backup : {backup}")

"""## Section 2 — Track and Analyse Issues

List (counter/index change/slice), Set (all ops), Dict (build by loop, keys/values/items,
pop, grouping, top without max())

### 2.1. Get 5 Issues Input from the user
"""

issues = []  # Should be five issues

def get_issue():
    """
    Collects issue details from user input with validation logic.
    Reuses get_validated_input for type, priority, and status fields.
    Uses get_validated_alpha for free-text fields that should not be blank.
    """
    print("\n--- New Issue Entry ---")
    issue_id = input("Enter Issue ID: ").strip()

    title = get_validated_alpha("Enter Issue title: ", "Issue title")

    # Validating Issue Type
    issue_type = get_validated_input(
        "Enter issue type (Bug/Feature): ",
        ["Bug", "Feature"]
    )

    # Validating Priority
    priority = get_validated_input(
        "Enter issue priority (Critical/High/Medium/Low): ",
        ["Critical", "High", "Medium", "Low"]
    )

    reporter = get_validated_alpha("Enter issue reporter: ", "Reporter")

    # Validating Status
    status = get_validated_input(
        "Enter issue status (Open/In Progress/Resolved): ",
        ["Open", "In Progress", "Resolved"]
    )

    return {
        "id": issue_id,
        "title": title,
        "type": issue_type,
        "priority": priority,
        "reporter": reporter,
        "status": status
    }

# collect exactly 5 issues
while len(issues) < 5:
    try:
        issue = get_issue()
        issues.append(issue)
        print(f"Issue {len(issues)}/5 added successfully.")
    except KeyboardInterrupt:
        print("\nProcess interrupted by user.")
        break

print("\nFinal Issue List:")
for item in issues:
    print(item)

"""### 2.2. List, Set, and Dictionary Operations"""

# Count `Open` issues using a loop and counter
open_count = 0
for issue in issues:
    if issue["status"] == "Open":
        open_count += 1

print(f"Open issues : {open_count}")

# Change the first issue's priority to 'Critical' using its index
issues[0]["priority"] = "Critical"
print(f"First issue → priority updated to Critical.")

# Use slicing to print the last two issues
print(f"Last two issues : {issues[-2:]}")

print(dash)

# Build reporters set from issues (loop)
reporters = set()
for issue in issues:
    reporters.add(issue["reporter"])

# Build tech_stack set from contributors (loop)
tech_stack = set()
for c in contributors:
    tech_stack.add(c["language"])

# add() one more technology manually
tech_stack.add("Rust")

# discard() one that may or may not exist — safe even if absent
tech_stack.discard("Cobol")

print(f"reporters : {reporters}")
print(f"tech_stack : {tech_stack}")

# union() both sets
all_items = reporters.union(tech_stack)
print(f"union : {all_items}")

# intersection() to find common items
common = reporters.intersection(tech_stack)
print(f"intersection : {common}")

# difference() to find reporters not in tech_stack
diff = reporters.difference(tech_stack)
print(f"difference : {diff}")

# Check if 'Critical' is in a set of all priorities
all_priorities = set()
for issue in issues:
    all_priorities.add(issue["priority"])

if "Critical" in all_priorities:
    print(f"Critical present : YES — flag for immediate review.")
else:
    print(f"Critical present : NO — no immediate flags.")

print(dash)

# Build priority_count dict by looping — map each priority to its count
priority_count = {}
for issue in issues:
    p = issue["priority"]
    if p in priority_count:
        priority_count[p] += 1
    else:
        priority_count[p] = 1

# Use keys(), values(), and items() each at least once when printing
print(f"priority keys : {priority_count.keys()}")
print(f"priority values : {priority_count.values()}")

# print("Priority breakdown:")
# for k, v in priority_count.items():
#     print(f"  {k} : {v}")

# print(dash)

# Build status_groups dict — each key is a status, each value is a list of issue titles
status_groups = {}
for issue in issues:
    s = issue["status"]
    if s in status_groups:
        status_groups[s].append(issue["title"])
    else:
        status_groups[s] = [issue["title"]]

# Print status groups matching expected output format
parts = []
for s, titles in status_groups.items():
    parts.append(f"{s} : {titles}")
print(f"Status Groups → {' | '.join(parts)}")

# print(dash)

reporter_count = {}
for issue in issues:
    r = issue["reporter"]
    if r in reporter_count:
        reporter_count[r] += 1
    else:
        reporter_count[r] = 1

top_reporter = ""
top_count = 0
for r, count in reporter_count.items():
    if count > top_count:
        top_count = count
        top_reporter = r

print(f"Top reporter : {top_reporter} ({top_count} issues)")

# Use pop() to remove the 'type' key from the first issue and print the result
issues[0].pop("type") # called only once

print(f"After pop('type') : {issues[0]}")

"""## Section 3 — Save, Read and Report


"""

import os
import csv

# Create a folder named after the project (from tuple, lowercase, underscores)
folder_name = project[0].lower().replace(" ", "_")

# Check with os.path.exists() before creating skip if it already exists
if not os.path.exists(folder_name):
    os.makedirs(folder_name)
    print(f"Folder created : {folder_name}/")
else:
    print(f"Folder already exists : {folder_name}/")

# Use os.path.join() for all paths
report_path = os.path.join(folder_name, "project_report.txt")

# Build priority breakdown string dynamically
priority_str = " ".join([f"{k}:{v}" for k, v in priority_count.items()])

# Wrap all file writing in try/except IOError
try:
    with open(report_path, "w") as f:
        f.write(f"{line}\n")
        f.write(f" {project[0]} — PROJECT REPORT\n")
        f.write(f"{line}\n\n")

        # Project info
        f.write(f"Project  : {project[0]}\n")
        f.write(f"Version  : {project[1]}\n")
        f.write(f"Year     : {project[2]}\n")
        f.write(f"Language : {project[3]}\n")
        f.write(f"Lead     : {project[4]}\n\n")

        # Contributors
        f.write(f"--- Contributors ({len(contributors)}) ---\n")
        for c in contributors:
            f.write(f"  {c['name']} | {c['role']} | {c['language']} | {c['commits']} commits | {c['country']}\n")
        f.write(f"\n")

        # Issues
        f.write(f"--- Issues ({len(issues)}) ---\n")
        for issue in issues:
            f.write(f"  {issue['id']} | {issue['title']} | {issue['priority']} | {issue['reporter']} | {issue['status']}\n")
        f.write(f"\n")

        # Analysis
        f.write(f"--- Analysis ---\n")
        f.write(f"Open issues  : {open_count}\n")
        f.write(f"Reporters    : {reporters}\n")
        f.write(f"Tech Stack   : {tech_stack}\n")
        f.write(f"Top Reporter : {top_reporter} ({top_count} issues)\n")
        f.write(f"Priority     : {priority_str}\n\n")

        # Status groups
        f.write(f"--- Status Groups ---\n")
        for s, titles in status_groups.items():
            f.write(f"  {s} : {titles}\n")

        f.write(f"{line}\n")

    print(f"Report saved : {report_path}")
except IOError as e:
    print(f"IOError writing report: {e}")

csv_path = os.path.join(folder_name, "issues.csv")

# Wrap all file writing in try/except IOError
try:
    with open(csv_path, "w", newline="") as f:
        writer = csv.writer(f)

        # Header: id,title,priority,reporter,status
        writer.writerow(["id", "title", "priority", "reporter", "status"])

        # One row per issue
        for issue in issues:
            writer.writerow([
                issue["id"],
                issue["title"],
                issue["priority"],
                issue["reporter"],
                issue["status"]
            ])

    print(f"CSV saved : {csv_path}")
except IOError as e:
    print(f"IOError writing CSV: {e}")

# Print folder contents with os.listdir()
print(f"Files saved : {os.listdir(folder_name)}")

# Wrap reading in try/except FileNotFoundError
try:
    # read() — print full file content
    print(f"--- read() ---")
    with open(report_path, "r") as f:
        content = f.read()
    print(content)

    # readline() — print first two lines only
    print(f"--- readline() ---")
    with open(report_path, "r") as f:
        first_line = f.readline().rstrip()
        second_line = f.readline().rstrip()
    print(f"Line 1 : {first_line}")
    print(f"Line 2 : {second_line}")

    # readlines() — count total lines, print only lines containing 'Critical' or 'High'
    print(f"--- readlines() ---")
    with open(report_path, "r") as f:
        all_lines = f.readlines()

    total_lines = len(all_lines)

    critical_high_count = 0
    for l in all_lines:
        if "Critical" in l or "High" in l:
            critical_high_count += 1
            print(f"  {l.rstrip()}")

    print(f"Total lines : {total_lines} Critical/High lines : {critical_high_count}")

except FileNotFoundError as e:
    print(f"FileNotFoundError: {e}")

print(dash)

print(line)
print(f" {project[0]} — FINAL SUMMARY")
print(line)
print(f"Project : {project[0]} Version : {project[1]} Lead : {project[4]}")
print(f"Contributors : {len(contributors)} Names : {names}")
print(f"Tech Stack : {tech_stack}")
print(f"Issues : {len(issues)} Open : {open_count} Reporters : {len(reporters)}")
print(f"Top Reporter : {top_reporter} ({top_count} issues)")
print(f"{priority_str}")
print(f"Report : {report_path}")
print(f"CSV    : {csv_path}")
print(line)
print(f"{project[0]} complete. Thank you for contributing to open source!")
print(line)

"""## Bonus Section (10 points)

List comprehension with compound condition, append mode, readlines() last 6 lines

### Part 1: Urgent Issues via List Comprehension
"""

# Using a single line of list comprehension, build urgent — titles of all issues
# where priority is 'Critical' or 'High'
urgent = [issue["title"] for issue in issues if issue["priority"] in ("Critical", "High")]

print(f"Urgent issues : {urgent}")
print(f"Count : {len(urgent)}")

"""### Part 2: Append Urgent Issues to Report"""

# Open project_report.txt in append mode ('a')
try:
    with open(report_path, "a") as f:
        f.write(f"\n--- URGENT ISSUES ---\n")
        for title in urgent:
            f.write(f"  - {title}\n")
        f.write(f"{line}\n")
    print(f"Urgent section appended to {report_path}")
except IOError as e:
    print(f"IOError appending to report: {e}")

# Use readlines() to print the last 6 lines and confirm the append worked
try:
    with open(report_path, "r") as f:
        all_lines = f.readlines()

    print(f"\n--- Last 6 lines ---")
    for l in all_lines[-6:]:
        print(l.rstrip())
except FileNotFoundError as e:
    print(f"FileNotFoundError: {e}")